[package]
name = "madrpc-client"
version.workspace = true
edition.workspace = true

[dependencies]
madrpc-common = { path = "../madrpc-common" }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
serde_json = "1.0"
