[package]
name = "madrpc-orchestrator"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3"
madrpc-common = { path = "../madrpc-common" }
madrpc-metrics = { path = "../madrpc-metrics" }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
