[package]
name = "simple-test"
version = "0.1.0"
edition = "2021"

[dependencies]
madrpc-client = { path = "../../crates/madrpc-client" }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
tracing-subscriber = "0.3"
